import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Learning App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="flex gap-4 bg-amber-400 p-2 items-center justify-center">
          <Link href={`/`}>Home</Link>
          <Link href={`/services`}>Services</Link>
          <Link href={`/about`}>About</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
