import "./globals.css";

export const metadata = {
  title: "Learning App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <h2>Hii</h2>
      {children}</body>
    </html>
  );
}
