export const metadata = {
  title: "About | Learning App",
  description: "Generated by create next app",
};

export default function AboutLayout({ children }) {
  return (
    <section lang="en">
      <h1>About Header Custom Layout</h1>
      <div>{children}</div>
    </section>
  );
}
