export default [
  {
    name: "Moldova",
    flag: "https://flagcdn.com/md.svg",
    population: 2617820,
    region: "Europe",
    capital: "Chișinău",
  },
  {
    name: "United States",
    flag: "https://flagcdn.com/us.svg",
    population: 329484123,
    region: "Americas",
    capital: "Washington, D.C.",
  },
  {
    name: "India",
    flag: "https://flagcdn.com/in.svg",
    population: 1380004385,
    region: "Asia",
    capital: "New Delhi",
  },
  {
    name: "Brazil",
    flag: "https://flagcdn.com/br.svg",
    population: 212559409,
    region: "Americas",
    capital: "Brasília",
  },
  {
    name: "Iceland",
    flag: "https://flagcdn.com/is.svg",
    population: 366425,
    region: "Europe",
    capital: "Reykjavík",
  },
  {
    name: "Afghanistan",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
    population: 40218234,
    region: "Asia",
    capital: "Kabul",
  },
  {
    name: "Åland Islands",
    flag: "https://flagcdn.com/ax.svg",
    population: 28875,
    region: "Europe",
    capital: "Mariehamn",
  },
  {
    name: "Albania",
    flag: "https://flagcdn.com/al.svg",
    population: 2837743,
    region: "Europe",
    capital: "Tirana",
  },
  {
    name: "Algeria",
    flag: "https://flagcdn.com/dz.svg",
    population: 44700000,
    region: "Africa",
    capital: "Algiers",
  },
  {
    name: "Germany",
    flag: "https://flagcdn.com/de.svg",
    population: 83240525,
    region: "Europe",
    capital: "Berlin",
  },
  {
    name: "France",
    flag: "https://flagcdn.com/fr.svg",
    population: 67391582,
    region: "Europe",
    capital: "Paris",
  },
  {
    name: "Italy",
    flag: "https://flagcdn.com/it.svg",
    population: 59554023,
    region: "Europe",
    capital: "Rome",
  },
  {
    name: "Spain",
    flag: "https://flagcdn.com/es.svg",
    population: 47351567,
    region: "Europe",
    capital: "Madrid",
  },
  {
    name: "United Kingdom",
    flag: "https://flagcdn.com/gb.svg",
    population: 67215293,
    region: "Europe",
    capital: "London",
  },
  {
    name: "China",
    flag: "https://flagcdn.com/cn.svg",
    population: 1402112000,
    region: "Asia",
    capital: "Beijing",
  },
  {
    name: "Japan",
    flag: "https://flagcdn.com/jp.svg",
    population: 125800000,
    region: "Asia",
    capital: "Tokyo",
  },
  {
    name: "South Korea",
    flag: "https://flagcdn.com/kr.svg",
    population: 51780579,
    region: "Asia",
    capital: "Seoul",
  },
  {
    name: "Australia",
    flag: "https://flagcdn.com/au.svg",
    population: 25687041,
    region: "Oceania",
    capital: "Canberra",
  },
  {
    name: "New Zealand",
    flag: "https://flagcdn.com/nz.svg",
    population: 5084300,
    region: "Oceania",
    capital: "Wellington",
  },
  {
    name: "Canada",
    flag: "https://flagcdn.com/ca.svg",
    population: 38005238,
    region: "Americas",
    capital: "Ottawa",
  },
  {
    name: "Mexico",
    flag: "https://flagcdn.com/mx.svg",
    population: 128932753,
    region: "Americas",
    capital: "Mexico City",
  },
  {
    name: "Argentina",
    flag: "https://flagcdn.com/ar.svg",
    population: 45376763,
    region: "Americas",
    capital: "Buenos Aires",
  },
  {
    name: "Egypt",
    flag: "https://flagcdn.com/eg.svg",
    population: 102334403,
    region: "Africa",
    capital: "Cairo",
  },
  {
    name: "South Africa",
    flag: "https://flagcdn.com/za.svg",
    population: 59308690,
    region: "Africa",
    capital: "Pretoria",
  },
  {
    name: "Nigeria",
    flag: "https://flagcdn.com/ng.svg",
    population: 206139587,
    region: "Africa",
    capital: "Abuja",
  },
  {
    name: "Russia",
    flag: "https://flagcdn.com/ru.svg",
    population: 144104080,
    region: "Europe",
    capital: "Moscow",
  },
  {
    name: "Turkey",
    flag: "https://flagcdn.com/tr.svg",
    population: 84339067,
    region: "Asia",
    capital: "Ankara",
  },
  {
    name: "Saudi Arabia",
    flag: "https://flagcdn.com/sa.svg",
    population: 34813867,
    region: "Asia",
    capital: "Riyadh",
  },
  {
    name: "Sweden",
    flag: "https://flagcdn.com/se.svg",
    population: 10353442,
    region: "Europe",
    capital: "Stockholm",
  },
  {
    name: "Norway",
    flag: "https://flagcdn.com/no.svg",
    population: 5379475,
    region: "Europe",
    capital: "Oslo",
  },
  {
    name: "Netherlands",
    flag: "https://flagcdn.com/nl.svg",
    population: 17441139,
    region: "Europe",
    capital: "Amsterdam",
  },
  {
    name: "Belgium",
    flag: "https://flagcdn.com/be.svg",
    population: 11589616,
    region: "Europe",
    capital: "Brussels",
  },
  {
    name: "Switzerland",
    flag: "https://flagcdn.com/ch.svg",
    population: 8636896,
    region: "Europe",
    capital: "Bern",
  },
  {
    name: "Austria",
    flag: "https://flagcdn.com/at.svg",
    population: 8917205,
    region: "Europe",
    capital: "Vienna",
  },
  {
    name: "Portugal",
    flag: "https://flagcdn.com/pt.svg",
    population: 10196707,
    region: "Europe",
    capital: "Lisbon",
  },
];
