POST  http://localhost:8082/user/register
Content-Type: application/json

{
    "fullname": "ROhan Rawat",
    "username": "rohan.rawat@123",
    "email": "rohan.rawat@gmail.com"
}
#####
GET  http://localhost:8082/user/all
Authorization: Abracadabra
#####
GET  http://localhost:8082/user/robin.rawat@123

###############################           Discussion Routes           #################################
POST  http://localhost:8082/discussion/new
Content-Type: application/json

{
    "title": "Death note Blogs",
    "author": ["Kira"],
    "content": "It's rank 1 anime in the world"
}
##### 